/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package borrowequipment;

import java.awt.Container;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.*;
/**
 *
 * @author smurf
 */
public class ThirdPage extends javax.swing.JFrame {
    Connection con;
    int student_id;
    /**
     * Creates new form ThirdPage
     */
    
    public ThirdPage(){
        initComponents();
    }
    
    public ThirdPage(Connection con, int id) {
        initComponents();
        this.con = con;
        this.student_id = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        broomInp = new javax.swing.JTextField();
        mopInp = new javax.swing.JTextField();
        laptopInp = new javax.swing.JTextField();
        powerBarInp = new javax.swing.JTextField();
        borrowBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Broom");

        jLabel2.setText("Mop");

        jLabel3.setText("Laptop");

        jLabel4.setText("Power Bar");

        broomInp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                broomInpActionPerformed(evt);
            }
        });

        borrowBtn.setText("borrow");
        borrowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(powerBarInp, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(laptopInp)
                    .addComponent(mopInp)
                    .addComponent(broomInp))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(cancelBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(borrowBtn)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(broomInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mopInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(laptopInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(powerBarInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrowBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public boolean isInteger(String input){
        try{
            Integer.parseInt(input);
            System.out.println(Integer.parseInt(input));
            return true;
        }catch(NumberFormatException ex){
            return false;
        }
    }
    
    private void borrowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowBtnActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        if(!isInteger(broomInp.getText())){
            JOptionPane.showMessageDialog(frame, "Input only integer between 0-1", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(!isInteger(mopInp.getText())){
            JOptionPane.showMessageDialog(frame, "Input only integer between 0-1", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(!isInteger(laptopInp.getText())){
            JOptionPane.showMessageDialog(frame, "Input only integer between 0-1", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(!isInteger(powerBarInp.getText())){
            JOptionPane.showMessageDialog(frame, "Input only integer between 0-1", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            try{
                Statement stmt = con.createStatement();
                if(Integer.parseInt(broomInp.getText()) > 0){
                    System.out.println("wow");
                    boolean isReady = true;
                    ResultSet rs = stmt.executeQuery("select equipment_id from equipment_student");
                    while(rs.next()){
                        System.out.println(rs.getString(1));
                        if((String)rs.getString(1) == "E0001"){
                            System.out.println("not");
                            JOptionPane.showMessageDialog(frame, "This equipment is not ready for borrow", "Error", JOptionPane.ERROR_MESSAGE);
                            isReady = false;
                        }
                    }
                    if(isReady){
                        stmt.executeUpdate("insert into equipment_student values (" + student_id + ", 'E0001')");
                        JOptionPane.showMessageDialog(frame, "Borrow completed", "Complete", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                else if(Integer.parseInt(mopInp.getText()) > 0){
                    boolean isReady = true;
                    ResultSet rs = stmt.executeQuery("select equipment_id from equipment_student");
                    while(rs.next()){
                        if(rs.getString(1) == "E0002"){
                            JOptionPane.showMessageDialog(frame, "This equipment is not ready for borrow", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    if(isReady){
                        stmt.executeUpdate("insert into equipment_student values (" + student_id + ", 'E0002')");
                        JOptionPane.showMessageDialog(frame, "Borrow completed", "Complete", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                else if(Integer.parseInt(laptopInp.getText()) > 0){
                    boolean isReady = true;
                    ResultSet rs = stmt.executeQuery("select equipment_id from equipment_student");
                    while(rs.next()){
                        if(rs.getString(1) == "E0003"){
                            JOptionPane.showMessageDialog(frame, "This equipment is not ready for borrow", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    if(isReady){
                        stmt.executeUpdate("insert into equipment_student values (" + student_id + ", 'E0003')");
                        JOptionPane.showMessageDialog(frame, "Borrow completed", "Complete", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                else if(Integer.parseInt(powerBarInp.getText()) > 0){
                    boolean isReady = true;
                    ResultSet rs = stmt.executeQuery("select equipment_id from equipment_student");
                    while(rs.next()){
                        if(rs.getString(1) == "E0004"){
                            JOptionPane.showMessageDialog(frame, "This equipment is not ready for borrow", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    if(isReady){
                        stmt.executeUpdate("insert into equipment_student values (" + student_id + ", 'E0004')");
                        JOptionPane.showMessageDialog(frame, "Borrow completed", "Complete", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                System.out.println("didn't match");
            }catch(Exception e){
                System.out.println("Error: " +e);
            }
        }
        
        
        
    }//GEN-LAST:event_borrowBtnActionPerformed

    private void broomInpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_broomInpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_broomInpActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FirstPage().setVisible(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThirdPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThirdPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThirdPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThirdPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThirdPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrowBtn;
    private javax.swing.JTextField broomInp;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField laptopInp;
    private javax.swing.JTextField mopInp;
    private javax.swing.JTextField powerBarInp;
    // End of variables declaration//GEN-END:variables
}
